Add some .env file checks

diff --git a/Scripts/Actions/start b/Scripts/Actions/start
--- a/Scripts/Actions/start
+++ b/Scripts/Actions/start
@@ -1,5 +1,10 @@
 ﻿#!/bin/bash
 
+if [ ! -f ".env" ]; then
+  echo ".env file not found! Exiting..."
+  exit 1
+fi
+
 # Extract the service name
 SERVICE_NAME="$1"
 . "./Scripts/Services/$SERVICE_NAME"
diff --git a/Scripts/Actions/update b/Scripts/Actions/update
--- a/Scripts/Actions/update
+++ b/Scripts/Actions/update
@@ -9,4 +9,9 @@ SERVICE_NAME="$1"
 git fetch
 git pull
 
+if [ ! -f ".env" ]; then
+  echo ".env file not found! Exiting..."
+  exit 1
+fi
+
 "docker compose" "$COMPOSE_TARGETS" "up -d" 
